[[providers]]
name = "space"
kind = "text"
resource = "space.txt"

[[providers]]
name = "film"
kind = "csv"
resource = "film.csv"

[[providers]]
name = "deaths"
kind = "sqlite"
resource = "deaths.db"

[[providers]]
name = "annual"
kind = "text"
resource = "annual.txt"

[[providers]]
name = "todayserver"
kind = "web"
resource = "https://todayserver-89bb2a1b2e80.herokuapp.com/api/v1/events"