[[providers]]
name = "compsci"
kind = "csv"
resource = "compsci.csv"

[[providers]]
name = "programming"
kind = "text"
resource = "programming.txt"

[[providers]]
name = "history"
kind = "text"
resource = "history.txt"

[[providers]]
name = "events-db"
kind = "sqlite"
resource = "events.db"

[[providers]]
name = "todayserver"
kind = "web"
resource = "https://todayserver-89bb2a1b2e80.herokuapp.com/api/v1/events"